name: Build
on:
  push:
    branches:
      - v4
jobs:
  build:
    env:
      RUNNER_TOOL_CACHE: /toolcache
    runs-on: ubuntu-latest
    steps:
      - run: git config --global core.quotepath false
      - name: Install apt packages
        run: apt update && apt install -y rsync
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: https://github.com/actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - run: npm i
      - run: npx quartz build
      - name: Create private key
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > /tmp/act_runner_key
          chmod 600 /tmp/act_runner_key
      - name: rsync public directory
        run: |
          rsync -avz --delete -e "ssh -i /tmp/act_runner_key -p ${{ vars.WEBSERVER_PORT }}-o StrictHostKeyChecking=no" ${{ gitea.workspace }}/public/* ${{ vars.WEBSERVER_USER }}@${{ vars.WEBSERVER_HOST }}:/var/www/html